# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

services:
  time-service:
    build: ./time-service
    ports:
          - 8080:8080
          - 8081:8081
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADDRESS: "8081"